GameStored.WebMVC/Controllers/DevelopersController.cs
using GameStoredTwo.Models.Developer;
using GameStoredTwo.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GameStored.WebMVC.Controllers
{
        [Authorize]
        public class DeveloperController: Controller
        {
            private DeveloperService CreateDeveloperService()
            {
                var service = new DeveloperService();
                return service;
            }

            // Get: Developer
            public ActionResult Index()
            {
                var service = CreateDeveloperService();
                var model = service.GetDevelopers();
                return View(model);
            }

            public ActionResult Create()
            {
                return View();
            }

            // Post
            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Create(DeveloperCreate model)
            {
                if (!ModelState.IsValid) return View(model);
                var service = CreateDeveloperService();
                if (service.CreateDeveloper(model))
                {
                    TempData["SaveResult"] = "Deveolper has been Created.";
                    return RedirectToAction("Index");
                };
                ModelState.AddModelError("", "Developer could not be Created.");
                return View(model);
            }

            public ActionResult Details(int id)
            {
                var svc = CreateDeveloperService();
                var model = svc.GetDeveloperByID(id);
                return View(model);
            }

            public ActionResult Edit(int id)
            {
                var service = CreateDeveloperService();
                var detail = service.GetDeveloperByID(id);
                var model = new DeveloperEdit
                {
                    DeveloperID = detail.DeveloperID,
                    DeveloperName = detail.DeveloperName
                };
                return View(model);
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Edit(int id, DeveloperEdit model)
            {
                if (!ModelState.IsValid) return View(model);

                if(model.DeveloperID != id)
                {
                    ModelState.AddModelError("", "DeveoperID Mismatch");
                    return View(model);
                }
                var service = CreateDeveloperService();

                if (service.UpdateDeveloper(model))
                {
                    TempData["SaveResult"] = "The Developer was Updated.";
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "The Developer could not be Updated.");
                return View(model);
            }

            [ActionName("Delete")]
            public ActionResult Delete(int id)
            {
                var svc = CreateDeveloperService();
                var model = svc.GetDeveloperByID(id);
                return View(model);
            }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteDeveloper(int id)
        {
            var service = CreateDeveloperService();
            service.DeleteDeveloper(id);
            TempData["SaveResult"] = "The Developer was Deleted.";
            return RedirectToAction("Index");
        }
    }
}

GameStored.WebMVC/Controllers/PublishersController.cs
using GameStoredTwo.Models.Publisher;
using GameStoredTwo.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GameStored.WebMVC.Controllers
{
    [Authorize]
    public class PublisherController : Controller
    {
        private PublisherService CreatePublisherService()
        {
            var service = new PublisherService();
            return service;
        }

        // Get: Publisher
        public ActionResult Index()
        {
            var service = CreatePublisherService();
            var model = service.GetPublishers();
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        // Post: Publisher
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PublisherCreate model)
        {
            if (!ModelState.IsValid) return View(model);
            var service = CreatePublisherService();
            if (service.CreatePublisher(model))
            {
                TempData["SaveResult"] = "Publisher has been Created.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Publisher could not be Created.");
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = CreatePublisherService();
            var model = svc.GetPublisherByID(id);
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreatePublisherService();
            var detail = service.GetPublisherByID(id);
            var model = new PublisherEdit
            {
                PublisherID = detail.PublisherID,
                PublisherName = detail.PublisherName
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PublisherEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.PublisherID != id)
            {
                ModelState.AddModelError("", "PublisherID Mismatch");
                return View(model);
            }
            var service = CreatePublisherService();

            if (service.UpdatePublisher(model))
            {
                TempData["SaveResult"] = "The Publisher was Updated.";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "The Publisher could not be Updated.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreatePublisherService();
            var model = svc.GetPublisherByID(id);
            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePublisher(int id)
        {
            var service = CreatePublisherService();
            service.DeletePublisher(id);
            TempData["SaveResult"] = "The Publisher was Deleted.";
            return RedirectToAction("Index");
        }
    }
}

GameStored.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GameStored - Part Duex!", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Consoles", "Index", "Consoles")</li>
                    <li>@Html.ActionLink("Games", "Index", "Games")</li>
                    <li>@Html.ActionLink("Developers", "Index", "Developer")</li>
                    <li>@Html.ActionLink("Publishers", "Index", "Publisher")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - dfdevaney</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>